[package]
name = "bevy_mod_preferences"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
directories = "5.0.1"
serde = "1.0.171"
serde_json = "1.0.103"
thiserror = "1.0.57"
