[package]
name = "bevy_saga"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
lazy_static = "1.5.0"
pest_derive = "2.7.15"
smallvec = "1.13.1"
thiserror = { workspace = true }
wasmtime = "27.0.0"
anyhow = "1.0.94"
bumpalo = "3.16.0"
walrus = "0.23.2"
peg = "0.8.4"
futures-lite = "2.5.0"
wasmprinter = "0.221.2"

[lints.clippy]
std_instead_of_core = "warn"
