[package]
name = "panoply_terrain"
version = "0.1.0"
edition = "2021"
private = true

[dependencies]
bevy = { workspace = true }
bitflags = { workspace = true }
lru = { workspace = true }
panoply_core = { workspace = true }
panoply_exemplar = { workspace = true }
rapier3d = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }
